services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./PGDATA:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flownet

  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - flownet


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    networks:
      - flownet


  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
    networks:
      - flownet

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - api-gateway
    networks:
      - flownet

  admin-service:
    build: ./admin-service
    container_name: admin-service
    ports:
      - "8085:8085"
    depends_on:
      - api-gateway
      - user-service
    environment:
      - USER_SERVICE_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - flownet


  wallet-service:
    build: ./wallet-service
    container_name: wallet-service
    ports:
      - "8082:8082"
    depends_on:
      - api-gateway
    networks:
      - flownet

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8089:8089"
    depends_on:
      - api-gateway
    networks:
      - flownet


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api-gateway
    networks:
      - flownet


networks:
  flownet:
    driver: bridge
